# Generated by Django 3.2.7 on 2023-02-03 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sherlock.jpg', upload_to='profile_pic')),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=5000)),
                ('account_address', models.CharField(max_length=50000)),
                ('organization_name', models.CharField(default='', max_length=50000)),
                ('organization_phone', models.IntegerField(default=0)),
                ('organization_address', models.CharField(default='', max_length=5000)),
                ('is_an_organization', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sherlock.jpg', upload_to='profile_pic')),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=5000)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=5000)),
                ('hashtag', models.CharField(max_length=5000)),
                ('goal', models.IntegerField(default=0)),
                ('raised', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
