# Generated by Django 3.2.7 on 2023-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_an_organization',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_address',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=50000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
