# Generated by Django 3.2.7 on 2023-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20230203_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
