# Generated by Django 3.2.7 on 2023-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50000)),
                ('account_address', models.CharField(max_length=50000)),
            ],
        ),
    ]
