# Generated by Django 3.2.7 on 2023-02-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.event'),
            preserve_default=False,
        ),
    ]
