# Generated by Django 3.2.7 on 2023-02-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_account_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_address',
            new_name='transaction_address',
        ),
    ]
