# Generated by Django 3.2.7 on 2023-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='transaction_address',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='sherlock.jpg', upload_to='blog'),
        ),
    ]
