# Generated by Django 3.2.7 on 2023-02-13 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_address', models.CharField(max_length=50000)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.donation')),
            ],
        ),
    ]
