# Generated by Django 3.2.7 on 2023-02-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_account_charityname'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='to_user',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
