# Generated by Django 3.2.7 on 2023-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20230213_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
