# Generated by Django 3.2.7 on 2023-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='sherlock.jpg', upload_to='products'),
        ),
    ]
