# Generated by Django 3.2.7 on 2023-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_blood_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blood',
            name='gender',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
