# Generated by Django 3.2.7 on 2023-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20230227_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
