# Generated by Django 4.2.1 on 2024-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fromaddress',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='donation',
            name='toaddress',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
