# Generated by Django 4.2.1 on 2024-03-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_donation_fromaddress_donation_toaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
