# Generated by Django 4.2.1 on 2024-03-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=50000),
            preserve_default=False,
        ),
    ]
